# Use the specified Node.js base image
FROM node:22.14.0-alpine

# Set the working directory for the notification-service
WORKDIR /app

# Copy all files into the container (files in .dockerignore will be excluded)
COPY . .

# Install dependencies using npm (leveraging package.json and package-lock.json)
RUN npm install

# Startup command to run the test producer script
CMD ["node", "test-producer.js"]
