# Use the specified Node.js base image
FROM node:22.14.0-alpine

# Set the working directory for the notification-service
WORKDIR /app

# Copy all files into the container (files in .dockerignore will be excluded)
COPY . .

# Install dependencies using npm (leveraging package.json and package-lock.json)
RUN npm install

# Expose the port on which the main service will run (adjust if needed)
EXPOSE 5002

# Startup command to run the main service
CMD ["node", "server.js"]
