apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: online-event-booking-ayaankhan
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: ayaankhan17/notification-service:4d51c3f7
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: notificationMongoUri
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: notificationRabbitmqUrl
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: notificationCeleryBrokerUrl
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: online-event-booking-ayaankhan
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
