apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: online-event-booking-ayaankhan
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ayaankhan17/user-service:c6daf204
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: userDatabaseUrl
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: userSecretKey
        - name: EVENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: userEventServiceUrl
        - name: BOOKING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: userBookingServiceUrl
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: online-event-booking-ayaankhan
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
