apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: online-event-booking-ayaankhan
  labels:
    app: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: ayaankhan17/booking-service:b4c7820f
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: bookingDatabaseUrl
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: bookingCeleryBrokerUrl
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: bookingSecretKey
        - name: EVENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: bookingEventServiceUrl
        - name: PAYMENT_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: bookingPaymentGatewayUrl
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: online-event-booking-ayaankhan
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
