name: Docker Compose Integration Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and start containers
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up -d
      
      - name: Wait for services to be ready
        run: |
          docker compose exec -T postgres pg_isready -U postgres
          docker compose exec -T mongodb mongosh --eval "db.stats()"
          docker compose exec -T rabbitmq rabbitmqctl await_startup
          sleep 15

      - name: Run availability checks
        run: |
          # Check User Service with retries and HTML validation
          curl --retry 5 --retry-delay 10 --retry-all-errors \
               --max-time 30 --fail-with-body \
               -sS http://localhost:8000/ | grep -q "<title>Login</title>"

          # Check Booking Service endpoint
          curl --retry 3 --retry-delay 5 \
               -sS http://localhost:5001/book_ticket || exit 1

          # Verify Event Service API
          curl --retry 3 --retry-delay 5 \
               -sS http://localhost:5000/api/events || exit 1

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.yml down -v