name: Docker Compose Integration Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and start containers
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up -d
      
      - name: Wait for services to be ready
        run: |
          docker-compose exec -T postgres pg_isready -U postgres
          docker-compose exec -T mongodb mongo --eval "db.stats()"
          docker-compose exec -T rabbitmq rabbitmqctl await_startup

      - name: Run integration tests
        run: |
          # Test user-service
          curl -sSf http://localhost:8000/healthcheck || exit 1
          
          # Test booking-service
          curl -sSf http://localhost:5001/healthcheck || exit 1
          
          # Test new-event-service
          curl -sSf http://localhost:5000/api/events || exit 1
          
          # Test notification-service
          curl -sSf http://localhost:5002/health || exit 1

      - name: Cleanup
        if: always()
        run: docker-compose -f docker-compose.yml down -v