name: EventService CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./new-event-service  # Path to the service directory
          file: ./new-event-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/event-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/event-service:${{ github.run_number }}