name: Notification Service CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service  # Adjust path if needed
          file: ./notification-service/Dockerfile.main
          push: ${{ github.event_name == 'push' }}  # Only push on direct pushes (not PRs)
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:${{ github.sha }}

  test-with-rabbitmq:
    needs: build-and-push
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672  # AMQP port
          - 15672:15672  # Management UI (optional)
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Navigate to notification-service
        run: cd ./notification-service

      - name: Install dependencies
        run: npm install

      - name: Run test producer
        run: node test-producer.js
        env:
          RABBITMQ_URL: amqp://guest:guest@localhost:5672