# .github/workflows/notification-service-ci.yml
name: Notification Service CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: write 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA as tag
        id: meta
        run: echo "tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          file: ./notification-service/Dockerfile.main
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:${{ steps.meta.outputs.tag }}

  test-with-rabbitmq:
    needs: build-and-push
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports: ["5672:5672"]
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Built Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:${{ needs.build-and-push.outputs.image-tag }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest

      - name: Run Test Producer via Docker
        run: |
          docker run --network host \
            -e RABBITMQ_URL="amqp://guest:guest@localhost:5672" \
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest \
            node test-producer.js

  update-k8s-manifest:
    needs: [build-and-push, test-with-rabbitmq]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with write access
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Sync remote main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase origin main


      - name: Update image in kubernetes/deployment-service-notification.yaml
        run: |
          FILE="kubernetes/deployment-service-notification.yaml"
          TAG=${{ needs.build-and-push.outputs.image-tag }}
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/notification-service:${TAG}"
          echo "Patching $FILE → image: $IMAGE"
          sed -i "s|image: .*|image: ${IMAGE}|" "$FILE"

      - name: Commit & push manifest update
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "ci: update notification-service image to ${{ needs.build-and-push.outputs.image-tag }}"
          push: true
